"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { Download, ArrowRight } from "lucide-react";
import { fetchReports, fetchMarkdownReport } from "@/lib/api";

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [activeReport, setActiveReport] = useState<string | null>(null);
  const [markdownContent, setMarkdownContent] = useState<string>("");
  const [viewLoading, setViewLoading] = useState<boolean>(false);

  useEffect(() => {
    async function loadReports() {
      try {
        setLoading(true);
        const res = await fetchReports();
        setReports(res.reports || []);
        if (res.reports && res.reports.length > 0) {
          // Open first report by default
          viewReport(res.reports[0].candidate_id);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadReports();
  }, []);

  const viewReport = async (candidateId: string) => {
    try {
      setActiveReport(candidateId);
      setViewLoading(true);
      const text = await fetchMarkdownReport(candidateId);
      setMarkdownContent(text);
    } catch (err) {
      console.error(err);
      setMarkdownContent("Failed to load markdown report.");
    } finally {
      setViewLoading(false);
    }
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 mb-1">
          <span className="text-xs font-mono text-cyan-400 font-semibold uppercase tracking-wider">
            Investigation Archive & Dossiers
          </span>
        </div>
        <h1 className="text-2xl font-bold font-mono text-white">Scientific Reports Catalog</h1>
        <p className="text-sm text-zinc-400 mt-1 max-w-2xl">
          Review, preview, and download formal scientific dossiers generated by the ACEI pipeline.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Report List */}
        <div className="space-y-3">
          <span className="text-xs font-mono font-bold text-zinc-300 uppercase">
            Available Dossiers ({reports.length})
          </span>

          <div className="space-y-2">
            {loading ? (
              <div className="p-4 rounded-lg bg-[#0d1322] border border-zinc-800 text-xs font-mono text-zinc-500">
                Loading dossiers...
              </div>
            ) : reports.length === 0 ? (
              <div className="p-4 rounded-lg bg-[#0d1322] border border-zinc-800 text-xs font-mono text-zinc-500">
                No dossiers found.
              </div>
            ) : (
              reports.map((rep) => {
              const isSelected = activeReport === rep.candidate_id;
              return (
                <div
                  key={rep.candidate_id}
                  onClick={() => viewReport(rep.candidate_id)}
                  className={`p-3.5 rounded-lg border transition-all cursor-pointer ${
                    isSelected
                      ? "bg-cyan-950/40 border-cyan-500/80 shadow-md shadow-cyan-950/20"
                      : "bg-[#0d1322] border-zinc-800 hover:border-zinc-700"
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-mono font-bold text-white">{rep.candidate_id}</span>
                    <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-zinc-900 border border-zinc-800 text-cyan-400">
                      {rep.claimed_type}
                    </span>
                  </div>

                  <div className="text-xs text-zinc-300 mt-2 font-mono truncate">
                    {rep.top_hypothesis}
                  </div>

                  <div className="flex items-center justify-between pt-2 mt-2 border-t border-zinc-800/80 text-[10px] font-mono text-zinc-500">
                    <span>STATUS: NOT_VALIDATED</span>
                    <div className="flex items-center gap-2">
                      <a
                        href={`/api/reports/${rep.candidate_id}/markdown`}
                        download
                        onClick={(e) => e.stopPropagation()}
                        className="text-cyan-400 hover:underline flex items-center gap-0.5"
                      >
                        <Download className="w-3 h-3" /> MD
                      </a>
                      <a
                        href={`/api/reports/${rep.candidate_id}/json`}
                        download
                        onClick={(e) => e.stopPropagation()}
                        className="text-cyan-400 hover:underline flex items-center gap-0.5"
                      >
                        <Download className="w-3 h-3" /> JSON
                      </a>
                    </div>
                  </div>
                </div>
              );
            }))}
          </div>
        </div>

        {/* Right Column: In-Browser Markdown Viewer */}
        <div className="lg:col-span-2 space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono font-bold text-zinc-300 uppercase">
              Dossier Preview: {activeReport || "None"}
            </span>

            {activeReport && (
              <div className="flex items-center gap-2">
                <Link
                  href={`/investigate/${activeReport}`}
                  className="px-2.5 py-1 rounded bg-zinc-900 hover:bg-zinc-800 text-xs font-mono text-cyan-400 border border-zinc-800 flex items-center gap-1"
                >
                  <span>Open Workstation</span>
                  <ArrowRight className="w-3 h-3" />
                </Link>
                <a
                  href={`/api/reports/${activeReport}/markdown`}
                  target="_blank"
                  rel="noreferrer"
                  className="px-2.5 py-1 rounded bg-zinc-900 hover:bg-zinc-800 text-xs font-mono text-zinc-300 border border-zinc-800 flex items-center gap-1"
                >
                  <Download className="w-3 h-3" />
                  <span>Download .md</span>
                </a>
              </div>
            )}
          </div>

          <div className="p-6 rounded-lg bg-[#060910] border border-zinc-800 min-h-[500px] max-h-[700px] overflow-y-auto font-mono text-xs text-zinc-300 space-y-4">
            {viewLoading ? (
              <div className="p-12 text-center text-zinc-500 font-mono">
                Loading report content...
              </div>
            ) : (
              <pre className="whitespace-pre-wrap font-mono text-xs leading-relaxed text-zinc-300">
                {markdownContent}
              </pre>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
